alg_name: 'DINM'
model_name: "/mnt/sdb/zjk/EasyEdit_dola/llama2-7b-chat"  # the vanilla LLM path  
model_class: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
device: 0
assistant_system_prompt: "The assistant:"

prefix_system_prompt: "The human:"

suffix_system_prompt: "A chat between a curious human and an artificial intelligence assistant.The assistant gives helpful, detailed, and polite answers to the human's questions.The assistant:"


# You can specify the edited layer for all data in advance, for example: layer: [31]
# if you set layers : [], DINM will locates the toxic layer for each instance in safety_editor.py
layers: []
num_steps: 10
batch_size: 1



# max_length is the maximum length of this LLM (llama2-7b-chat).
max_length: 2048

# if you use SafeEdit dataset to evaluate llama2-7b-chat, it is recommended to set max_output_length to 600 for the response by LLM. 
# For some role-playing attack prompts, LLMs may initially generate safe responses and then suddenly generate toxic text. Therefore, you should set enough max_output_length (600) to evaluate the safety of LLM.
max_output_length: 256
lr: 5e-4
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: 'model.layers.{}.mlp.down_proj.weight'
layer_module_tmp: 'model.layers.{}'
mlp_module_tmp: 'model.layers.{}.mlp'
attn_module_tmp: 'model.layers.{}.self_attn'
ln_f_module: 'model.norm'
lm_head_module: 'lm_head'
model_parallel: false
